# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-6647cbcd-ed3a-4205-9a2c-78e337e2f3bf";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."luks-6647cbcd-ed3a-4205-9a2c-78e337e2f3bf".device = "/dev/disk/by-uuid/6647cbcd-ed3a-4205-9a2c-78e337e2f3bf";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CE66-E001";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
