[colors.normal]
black = "0x3B4252"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xE5E9F0"
yellow = "0xEBCB8B"

[colors.primary]
background = "0x2E3440"
foreground = "0xD8DEE9"

[font]
size = 12

[font.normal]
family = "monospace"
style = "Regular"

[terminal.shell]
program = "/usr/bin/nu"

[window]
decorations = "full"
dynamic_padding = true
title = "Alacritty"

[terminal]
